version: '3.8'
services:
  mariadb:
    env_file: 
      - .env
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    hostname: mariadb
  wordpress:
    env_file:
      - .env
    container_name: WordPress
    depends_on:
      - mariadb
    build: ./requirements/WordPress 
    restart: always

#volumes: 
 # - db_data: {}